apiVersion: apps/v1
kind: Deployment
metadata:
  name: pulumi-eks-demo
  namespace: default
spec:
  selector:
    matchLabels:
      app: pulumi-eks-demo
  replicas: 1
  template:
    metadata:
      name: pulumi-eks-demo
      labels:
        app: pulumi-eks-demo
    spec:
      containers:
      - name: pulumi-eks-demo
        env:
          - name: POSTGRES_USER
            valueFrom:
              secretKeyRef:
                 name: postgres-secrets
                 key: username
          - name: POSTGRES_PASSWORD
            valueFrom:
              secretKeyRef:
                 name: postgres-secrets
                 key: password
          - name: POSTGRES_HOST
            valueFrom:
              configMapKeyRef:
                name: hostname-config
                key: postgres_host
        image: appurajacool2015/ekspulumispringbootpostgresrestapidemo:latest
